---
title: "Multivariate analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

# This file contains a multivariate analysis technique known as a 'Principal Component Analysis'. This tool is helpful in analyzing data sets with a large number of variables and allowing us to visualize the relationships between them all. It is a dimensionality reduction technique in which 'Principal Components' are constructed based off of the directions of maximum variation in the data set. It can be a powerful tool to quickly asses large data sets, with little work on our end.

# Here, I apply this technique to a suite of ocean based variables that
# dictate the amount of carbon sequestration in the ocean. However, I could
# apply this to many different situations/data sets.


# Load the required libraries:
suppressMessages(library(PCAtools))
suppressMessages(library(ggplot2))
suppressMessages(library(ggfortify))
suppressMessages(library(dplyr))
suppressMessages(library(ggpubr))
suppressMessages(library(viridis))


# Load in the appropriate data
data_2 <- read.csv("PCA_input.csv", skip = 0, header = TRUE, fill = TRUE)
data <- read.csv("Total_data.csv", skip = 0, header = TRUE, fill = TRUE)

```

Create the PCA and get a summary of the PCs
```{r}

# Index out specific categories:
total_split <- split(data, data$PCA_1)  # All data split

data <- total_split$Y  

# Select variables of interest: Exclude categorical data
xdf <- select(data, TEP_C, Nitrate, Chl, 
               DO, Temperature, MLD, POC) 

xdf_2 <- select(data, TEP, Nitrate, Chl, 
               DO, Temperature, MLD, POC) 

# Create the Principal components:
xpca <- prcomp(xdf, scale = TRUE, center = TRUE, scores = TRUE) 
xpca_2 <- prcomp(xdf_2, scale = TRUE, center = TRUE, scores = TRUE) 

# Obtain a summary of all the principal components:
summary(xpca)

# Call str() to look at the PCA object:
str(xpca)

# plot a histogram of the Principal components (PCs):
plot(xpca)

```

Plot the CPA using auto plot:
```{r}

# Plot the PCA:
PCA <- autoplot(xpca, data = data, colour = 'Group', loadings = TRUE, 
         loadings.colour = 'blue',loadings.label = TRUE, 
         loadings.label.size = 3, loadings.label.colour = 'black')

PCA_2 <- autoplot(xpca_2, data = data, colour = 'Group', loadings = TRUE, 
         loadings.colour = 'blue',loadings.label = TRUE, 
         loadings.label.size = 3, loadings.label.colour = 'black')

PCA <- PCA + 
  ylim(-0.4, 0.6) +
  xlim(-0.4, 0.4) +
  guides(fill = FALSE) +
  scale_color_manual(values = c(8, 9, 3, 6, 5, 13)) +
  theme_pubr()

PCA_2 <- PCA_2 + 
  ylim(-0.4, 0.6) +
  xlim(-0.4, 0.4) +
  guides(fill = FALSE) +
  scale_color_manual(values = c(8, 9, 3, 6, 5, 13)) +
  theme_pubr()

Figure <- ggarrange(PCA, PCA_2, common.legend = TRUE)

Figure 

# When viewing the results, we can see that specific variables such as 
# Temperature and %TEP (carbon gels) are more strongly expressed within the 
# 'summer group'. It is also apparent that the wintertime conditions 
# are very distinct from the other two groups.

pdf(file = "/Users/michaellivingston/Desktop/PCA_1.pdf",   # The directory you want to save the file in
    width = 10, # The width of the plot in inches
    height = 5) # The height of the plot in inches

Figure

dev.off()



```

# Create another set of PCAs using the second dataframe:
```{r}

xdf <- select(data_2, New_production, bSi_C, Nitrate, TEP, Chlorophyll, DO, Percent_small_cells, Temperature)


xpca <- prcomp(xdf, scale = TRUE, center = TRUE)


autoplot(xpca, data = data_2, colour = 'Group', shape = 'Season', loadings = TRUE, 
         loadings.colour = 'blue',loadings.label = TRUE, 
         loadings.label.size = 3, loadings.label.colour = 'black',
         frame = FALSE, frame.colour = 'Group')



```


# Render a 3D PCA using plotly
```{r}

# Redo the PCA calculations:

# Create the Principal components:
xpca <- princomp(xdf, scale = TRUE, center = TRUE, scores = T, cor = T) 

# Scores
scores <- xpca$scores
x <- scores[,1]
y <- scores[,2]
z <- scores[,3]


# Loadings
loads <- xpca$loadings

# Scale factor for loadings
scale.loads <- 5


# 3D plot
library(plotly)

p <- plot_ly() %>%
  add_trace(x=x, y=y, z=z,
            type="scatter3d", mode="markers",
            marker = list(color=y, 
               colorscale = c("#FFE1A1", "#683531"), 
               opacity = 0.7)) 

for (k in 1:nrow(loads)) {
   x <- c(0, loads[k,1])*scale.loads
   y <- c(0, loads[k,2])*scale.loads
   z <- c(0, loads[k,3])*scale.loads
   p <- p %>% add_trace(x=x, y=y, z=z,
            type="scatter3d", mode="lines",
            line = list(width=8),
            opacity = 1) 
}
print(p)


```






